const root=document.getElementById('root');
const DEFAULT_CONFIG={supabaseUrl:'',supabaseAnonKey:'',allowedDomain:'felg.app'};
const CONFIG=Object.assign({},DEFAULT_CONFIG,JSON.parse(localStorage.getItem('mh-config')||'{}'));
let sb=null;
if(CONFIG.supabaseUrl&&CONFIG.supabaseAnonKey&&window.supabase){sb=window.supabase.createClient(CONFIG.supabaseUrl,CONFIG.supabaseAnonKey)}
let state={user:null,mode:'login',view:'dashboard',items:[],profiles:[],msg:'',loading:false};
const views=['dashboard','zadania','projekty','social','kreacje','wydarzenia','partnerzy','magazyn','finanse','checklisty','notatki','ustawienia'];
function esc(v){return String(v??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function today(){return new Date().toISOString().slice(0,10)}
function showMsg(m){state.msg=m;render()}
function type(t){return state.items.filter(x=>x.type===t).map(x=>({id:x.id,visibility:x.visibility,owner_id:x.owner_id,...x.data}))}
function raw(id){return state.items.find(x=>x.id===id)}
function item(title,sub,actions=''){return `<div class="item"><div><h4>${esc(title)}</h4><p>${esc(sub)}</p></div><div>${actions}</div></div>`}
function del(id){return `<button class="btn sm del" onclick="removeItem('${id}')">Usuń</button>`}
function layout(title,desc,body,action=''){return `<div class="title"><div><h1>${title}</h1><p class="hint">${desc}</p></div>${action}</div>${body}`}
function render(){try{document.body.className='';if(!sb)return renderConfig();if(!state.user)return renderAuth();renderApp()}catch(e){root.innerHTML=`<div class="login"><div class="card"><h1>Błąd aplikacji</h1><p class="err">${esc(e.message)}</p><button class="btn" onclick="localStorage.removeItem('mh-config');location.reload()">Wyczyść konfigurację</button></div></div>`;console.error(e)}}
function renderConfig(){root.innerHTML=`<div class="login"><div class="log"><div class="hero"><div class="brand"><b class="mark">M</b><span>Marketing Hub</span></div><h1>Podłącz Supabase</h1><p>Wklej URL projektu oraz publishable key z Supabase.</p></div><div class="form"><h2>Konfiguracja</h2><input id="cfgUrl" class="inp" placeholder="SUPABASE_URL"><input id="cfgKey" class="inp" placeholder="SUPABASE_ANON_KEY / publishable key"><input id="cfgDomain" class="inp" value="${esc(CONFIG.allowedDomain)}"><button id="saveCfg" class="btn">Zapisz konfigurację</button><p class="hint">Domena bez @, np. felg.app</p></div></div></div>`;document.getElementById('saveCfg').onclick=()=>{localStorage.setItem('mh-config',JSON.stringify({supabaseUrl:document.getElementById('cfgUrl').value.trim(),supabaseAnonKey:document.getElementById('cfgKey').value.trim(),allowedDomain:document.getElementById('cfgDomain').value.trim()||'felg.app'}));location.reload()}}
function renderAuth(){root.innerHTML=`<div class="login"><div class="log"><div class="hero"><div class="brand"><b class="mark">M</b><span>Marketing Hub</span></div><h1>Logowanie do marketingu</h1><p>Zaloguj hasłem, utwórz konto z potwierdzeniem maila albo zresetuj hasło.</p><p>Dostęp: @${esc(CONFIG.allowedDomain)}</p></div><div class="form"><div class="auth-tabs"><button class="btn sec ${state.mode==='login'?'on':''}" onclick="state.mode='login';state.msg='';render()">Zaloguj</button><button class="btn sec ${state.mode==='signup'?'on':''}" onclick="state.mode='signup';state.msg='';render()">Utwórz konto</button><button class="btn sec ${state.mode==='reset'?'on':''}" onclick="state.mode='reset';state.msg='';render()">Reset</button></div><h2>${state.mode==='login'?'Zaloguj hasłem':state.mode==='signup'?'Utwórz konto':'Odzyskaj hasło'}</h2>${state.msg?`<div class="okbox">${esc(state.msg)}</div>`:''}<input id="email" class="inp" value="malgorzata.sliwa@felg.app" placeholder="e-mail">${state.mode!=='reset'?'<input id="password" class="inp" type="password" placeholder="hasło">':''}${state.mode==='signup'?'<input id="fullName" class="inp" placeholder="imię i nazwisko">':''}<button id="authBtn" class="btn">${state.mode==='login'?'Zaloguj':state.mode==='signup'?'Utwórz konto':'Wyślij reset hasła'}</button><p class="hint">Jeśli konto utworzono ręcznie w Supabase i ma hasło, użyj zakładki Zaloguj.</p></div></div></div>`;document.getElementById('authBtn').onclick=authAction}
async function authAction(){const email=document.getElementById('email').value.trim();const pass=document.getElementById('password')?.value||'';if(!email.toLowerCase().endsWith('@'+CONFIG.allowedDomain.toLowerCase()))return showMsg('Dostęp tylko dla @'+CONFIG.allowedDomain);showMsg('Sprawdzam...');try{if(state.mode==='login'){const {data,error}=await sb.auth.signInWithPassword({email,password:pass});if(error)throw error;state.user=data.user;await loadAll();return}if(state.mode==='signup'){if(pass.length<6)return showMsg('Hasło musi mieć minimum 6 znaków.');const full=document.getElementById('fullName')?.value||email.split('@')[0];const {error}=await sb.auth.signUp({email,password:pass,options:{emailRedirectTo:location.origin+location.pathname,data:{full_name:full}}});if(error)throw error;return showMsg('Konto utworzone. Potwierdź mail, a potem zaloguj się hasłem.')}if(state.mode==='reset'){const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)throw error;return showMsg('Wysłano link resetu hasła.')}}catch(e){showMsg('Błąd: '+e.message)}}
async function init(){if(!sb){render();return}const {data}=await sb.auth.getSession();state.user=data.session?.user||null;sb.auth.onAuthStateChange(async(ev,session)=>{state.user=session?.user||null;if(ev==='PASSWORD_RECOVERY'){const np=prompt('Wpisz nowe hasło');if(np){const {error}=await sb.auth.updateUser({password:np});alert(error?error.message:'Hasło zmienione')}}if(state.user)await loadAll();else render()});if(state.user)await loadAll();else render()}
async function loadAll(){state.loading=true;renderApp();const [items,profiles]=await Promise.all([sb.from('marketing_items').select('*').order('created_at',{ascending:false}),sb.from('marketing_profiles').select('*')]);state.items=items.data||[];state.profiles=profiles.data||[];state.loading=false;renderApp();if(items.error)alert(items.error.message)}
function renderApp(){const nav=views.map(v=>`<button class="${state.view===v?'on':''}" onclick="state.view='${v}';renderApp()"><b>${icon(v)}</b><span>${label(v)}</span></button>`).join('');root.innerHTML=`<div class="app"><aside class="side"><div class="brand"><b class="mark">M</b><span>Marketing Hub<br><small class="hint">Supabase</small></span></div><div class="prof"><div class="av">${esc((state.user?.email||'G')[0]).toUpperCase()}</div><div><b>${esc(state.user?.email||'')}</b><br><small class="hint">zalogowano</small></div></div><nav class="nav">${nav}</nav></aside><main class="main"><div class="top"><input class="inp" placeholder="Szukaj"><button class="btn" onclick="openAdd('task')">+ Zadanie</button><button class="btn sec" onclick="loadAll()">Odśwież</button><button class="btn sec" onclick="sb.auth.signOut()">Wyloguj</button></div>${state.loading?'<div class="loader">Ładowanie...</div>':''}${screen()}</main></div>${modalHtml()}`;bindUpload()}
function icon(v){return {dashboard:'🏠',zadania:'✅',projekty:'📁',social:'📱',kreacje:'🎨',wydarzenia:'🎤',partnerzy:'🤝',magazyn:'📦',finanse:'💳',checklisty:'☑️',notatki:'📝',ustawienia:'⚙️'}[v]||'•'}function label(v){return v[0].toUpperCase()+v.slice(1)}
function screen(){if(state.view==='dashboard')return dashboard();if(state.view==='zadania')return listScreen('task','Zadania','Kanban/lista pracy','title','status',true);if(state.view==='projekty')return listScreen('project','Projekty i kampanie','Cele, budżety, statusy','name','status');if(state.view==='social')return listScreen('social','Social Media','Posty i publikacje','title','channel');if(state.view==='kreacje')return listScreen('creative','Kreacje i grafiki','Briefy i formaty','name','status');if(state.view==='wydarzenia')return listScreen('event','Wydarzenia','Webinary, targi, eventy','name','date');if(state.view==='partnerzy')return listScreen('partner','Partnerzy','Bez klientów: dostawcy, media, wykonawcy','name','type');if(state.view==='magazyn')return magazyn();if(state.view==='finanse')return listScreen('finance','Finanse','Koszty, faktury, subskrypcje','name','amount');if(state.view==='checklisty')return checklisty();if(state.view==='notatki')return notatki();return ustawienia()}
function dashboard(){const tasks=type('task'),projects=type('project'),events=type('event'),cost=type('finance').reduce((a,b)=>a+(+b.amount||0),0);return layout('Dashboard','Centrum pracy marketingu',`<div class="grid c4"><div class="card metric"><small>Zadania</small><br><b>${tasks.length}</b></div><div class="card metric"><small>Projekty</small><br><b>${projects.length}</b></div><div class="card metric"><small>Wydarzenia</small><br><b>${events.length}</b></div><div class="card metric"><small>Koszty</small><br><b>${cost} zł</b></div></div><div class="grid c2" style="margin-top:14px"><div class="card"><h2>Ostatnie zadania</h2>${tasks.slice(0,6).map(x=>item(x.title,x.status,del(x.id))).join('')||'<p class="hint">Brak</p>'}</div><div class="card"><h2>Szybkie akcje</h2><button class="btn sec" onclick="seedDemo()">Dodaj dane startowe</button> <button class="btn sec" onclick="openAdd('note')">Notatka</button></div></div>`)}
function listScreen(t,title,desc,a,b){const arr=type(t);return layout(title,desc,`<div class="grid c2">${arr.map(x=>`<div class="card"><h2>${esc(x[a]||'(bez nazwy)')}</h2><p class="hint">${esc(x[b]||'')}</p>${del(x.id)}</div>`).join('')||'<div class="card">Brak danych.</div>'}</div>`,`<button class="btn" onclick="openAdd('${t}')">+ Dodaj</button>`)}
function magazyn(){const arr=type('warehouse');return layout('Magazyn','Biuro i Garaż',`<div class="grid c2"><div class="card"><h2>Biuro</h2>${arr.filter(x=>x.place==='Biuro').map(x=>item(x.name,(x.qty||0)+' szt.',del(x.id))).join('')||'<p class="hint">Pusto</p>'}</div><div class="card"><h2>Garaż</h2>${arr.filter(x=>x.place==='Garaż').map(x=>item(x.name,(x.qty||0)+' szt.',del(x.id))).join('')||'<p class="hint">Pusto</p>'}</div></div><div class="card" style="margin-top:14px"><h2>Pliki</h2><div id="drop" class="drop">Kliknij, aby wgrać pliki<input id="file" type="file" multiple hidden></div>${type('file').map(f=>item(f.name,Math.round((f.size||0)/1024)+' KB',`<button class="btn sm sec" onclick="downloadFile('${f.id}')">Pobierz</button> ${del(f.id)}`)).join('')}</div>`,`<button class="btn" onclick="openAdd('warehouse')">+ Materiał</button>`)}
function checklisty(){const arr=type('template');return layout('Checklisty','Szablony do wydarzeń i kampanii',`<div class="grid c2">${arr.map(x=>`<div class="card"><h2>${esc(x.name)}</h2><p>${(x.items||[]).map(i=>'☐ '+esc(i)).join('<br>')}</p>${del(x.id)}</div>`).join('')||'<div class="card">Brak checklist.</div>'}</div>`,`<button class="btn" onclick="openAdd('template')">+ Szablon</button>`)}
function notatki(){const arr=type('note');return layout('Notatki wizualne','Prywatne notatki widzisz tylko Ty',`<div class="grid c2">${arr.map(x=>`<div class="card"><span class="chip">${x.visibility==='private'?'prywatna':'wspólna'}</span><h2>${esc(x.title)}</h2><p>${esc(x.body)}</p>${del(x.id)}</div>`).join('')||'<div class="card">Brak notatek.</div>'}</div>`,`<button class="btn" onclick="openAdd('note')">+ Notatka</button>`)}
function ustawienia(){return layout('Ustawienia','Konto, zespół, Supabase',`<div class="grid c2"><div class="card"><h2>Konto</h2><p>${esc(state.user.email)}</p></div><div class="card"><h2>Konfiguracja</h2><button class="btn sec" onclick="localStorage.removeItem('mh-config');location.reload()">Zmień Supabase</button></div></div>`)}
function modalHtml(){return `<div id="modal" class="modal"><div class="box"><div style="display:flex;justify-content:space-between"><h2 id="modalTitle">Dodaj</h2><button class="btn sec" onclick="closeAdd()">✕</button></div><div id="modalBody"></div></div></div>`}
function openAdd(t){document.getElementById('modal').classList.add('on');document.getElementById('modalTitle').textContent='Dodaj: '+t;let html='';if(t==='note')html='<input id="f_title" class="inp" placeholder="Tytuł"><textarea id="f_body" class="inp" placeholder="Treść"></textarea><select id="f_visibility" class="inp"><option value="private">Prywatna</option><option value="team">Wspólna</option></select>';else if(t==='template')html='<input id="f_name" class="inp" placeholder="Nazwa"><textarea id="f_items" class="inp" placeholder="Punkty checklisty, każdy w nowej linii"></textarea>';else html='<input id="f_name" class="inp" placeholder="Nazwa"><input id="f_status" class="inp" placeholder="Status / typ"><input id="f_due" class="inp" placeholder="Termin lub kwota">';document.getElementById('modalBody').innerHTML=html+'<br><br><button class="btn" onclick="saveAdd(\''+t+'\')">Zapisz</button>'}
function closeAdd(){document.getElementById('modal').classList.remove('on')}
async function saveAdd(t){let data={},vis='team';if(t==='note'){data={title:val('title'),body:val('body'),visibility:val('visibility')};vis=val('visibility')||'private'}else if(t==='template'){data={name:val('name'),items:(val('items')||'').split('\n').filter(Boolean)}}else{data={name:val('name'),title:val('name'),status:val('status'),type:val('status'),due:val('due'),amount:Number(val('due'))||0,place:val('status')==='Garaż'?'Garaż':'Biuro',qty:Number(val('due'))||0}}await insert(t,data,vis);closeAdd();await loadAll()}
function val(x){return document.getElementById('f_'+x)?.value||''}
async function insert(type,data,visibility='team'){const {error}=await sb.from('marketing_items').insert({type,data,visibility,owner_id:state.user.id});if(error)alert(error.message)}
async function removeItem(id){if(!confirm('Usunąć?'))return;const r=raw(id);if(r?.type==='file'&&r.data.path)await sb.storage.from('marketing-files').remove([r.data.path]);const {error}=await sb.from('marketing_items').delete().eq('id',id);if(error)alert(error.message);await loadAll()}
async function seedDemo(){const rows=[{type:'task',data:{title:'Przygotować mailing',status:'Do zrobienia'},visibility:'team',owner_id:state.user.id},{type:'project',data:{name:'Kampania webinarowa',status:'W trakcie'},visibility:'team',owner_id:state.user.id},{type:'event',data:{name:'Webinar',date:'2026-07-10'},visibility:'team',owner_id:state.user.id},{type:'template',data:{name:'Webinar',items:['Landing','Mailing','Grafiki','Prezentacja','Nagranie']},visibility:'team',owner_id:state.user.id}];const {error}=await sb.from('marketing_items').insert(rows);if(error)alert(error.message);await loadAll()}
function bindUpload(){const d=document.getElementById('drop'),f=document.getElementById('file');if(!d)return;d.onclick=()=>f.click();f.onchange=()=>uploadFiles(f.files)}
async function uploadFiles(files){for(const file of [...files]){const path=`${state.user.id}/${Date.now()}-${file.name}`;const up=await sb.storage.from('marketing-files').upload(path,file);if(up.error){alert(up.error.message);continue}await insert('file',{name:file.name,size:file.size,path,mime:file.type},'team')}await loadAll()}
async function downloadFile(id){const r=raw(id);const {data,error}=await sb.storage.from('marketing-files').createSignedUrl(r.data.path,60);if(error)return alert(error.message);window.open(data.signedUrl,'_blank')}
window.addEventListener('error',e=>{root.innerHTML=`<div class="login"><div class="card"><h1>Błąd aplikacji</h1><p class="err">${esc(e.message)}</p><button class="btn" onclick="location.reload()">Odśwież</button></div></div>`});
init();
