const DEFAULT_CONFIG={supabaseUrl:'',supabaseAnonKey:'',allowedDomain:'felg.app'};
const CONFIG=Object.assign({},DEFAULT_CONFIG,window.MARKETING_HUB_CONFIG||JSON.parse(localStorage.getItem('mh-config')||'{}'));
const sb=(CONFIG.supabaseUrl&&CONFIG.supabaseAnonKey&&window.supabase)?window.supabase.createClient(CONFIG.supabaseUrl,CONFIG.supabaseAnonKey):null;
const today=()=>new Date().toISOString().slice(0,10);
const esc=x=>String(x??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
const $=x=>document.getElementById(x);
const labels={dash:'🏠 Dashboard',cal:'📅 Kalendarz',projects:'📁 Projekty',tasks:'✅ Zadania',social:'📱 Social Media',creative:'🎨 Kreacje',events:'🎤 Wydarzenia',partners:'🤝 Partnerzy',materials:'📦 Materiały',finance:'💳 Finanse',checks:'☑️ Checklisty',notes:'📝 Notatki',reports:'📊 Raporty',settings:'⚙️ Ustawienia'};
const typeMap={projects:'project',tasks:'task',events:'event',partners:'partner',files:'file',dropbox:'dropbox',warehouse:'warehouse',finance:'finance',social:'social',creative:'creative',templates:'template',assigned:'assigned_checklist',notes:'note'};
const seedItems=[{type:'project',visibility:'team',data:{name:'Kampania webinarowa',type:'kampania',status:'W trakcie',due:'2026-07-10',budget:4200,desc:'Mailing, social i materiały.'}},{type:'project',visibility:'team',data:{name:'Materiały targowe',type:'projekt',status:'Planowanie',due:'2026-08-04',budget:9800,desc:'Roll-upy, katalogi, gadżety.'}},{type:'task',visibility:'team',data:{title:'Przygotować mailing',status:'Do zrobienia',prio:'Wysoki',due:'2026-06-27',panel:'Ogólny'}},{type:'task',visibility:'team',data:{title:'Brief grafik webinarowych',status:'W trakcie',prio:'Wysoki',due:'2026-06-26',panel:'Kreacje'}},{type:'task',visibility:'team',data:{title:'Rozpisać 6 postów',status:'Do sprawdzenia',prio:'Normalny',due:'2026-06-29',panel:'Social'}},{type:'event',visibility:'team',data:{name:'Webinar Rejestracja 2.0',type:'Webinar',date:'2026-07-10',status:'W przygotowaniu'}},{type:'partner',visibility:'team',data:{name:'Drukarnia Premium Print',type:'Drukarnia',person:'Marta',email:'druk@example.pl',phone:'500111222',notes:'Katalogi i roll-upy'}},{type:'warehouse',visibility:'team',data:{name:'Roll-up FELG Dent',place:'Garaż',qty:3,min:1,cat:'Targi'}},{type:'warehouse',visibility:'team',data:{name:'Smycze',place:'Biuro',qty:120,min:50,cat:'Gadżety'}},{type:'finance',visibility:'team',data:{name:'Meta Ads',type:'Koszt kampanii',status:'Do opłacenia',amount:1200,due:'2026-06-30'}},{type:'finance',visibility:'team',data:{name:'Canva Pro',type:'Narzędzie płatne',status:'Subskrypcja',amount:55,due:'2026-07-01'}},{type:'social',visibility:'team',data:{channel:'LinkedIn',title:'Post zapraszający na webinar',status:'Draft',date:'2026-06-28'}},{type:'creative',visibility:'team',data:{name:'Key visual webinaru',format:'LinkedIn + mailing',status:'Brief',due:'2026-06-27'}},{type:'template',visibility:'team',data:{name:'Webinar',items:['Formularz zapisu','Mailing','Grafiki','Prezentacja','Przypomnienie 24h','Nagranie','Mail po wydarzeniu']}},{type:'template',visibility:'team',data:{name:'Targi',items:['Zgłoszenie','Opłata','Stoisko','Roll-upy','Katalogi','Gadżety','Transport','Raport']}}];
let state={session:null,user:null,view:'dash',panel:'Ogólny',q:'',authMode:'login',recover:false,theme:localStorage.getItem('mh-theme')||'ocean',mode:localStorage.getItem('mh-mode')||'light',items:[],profiles:[],loading:false,message:''};
function byType(t){return state.items.filter(i=>i.type===t).map(i=>({id:i.id,owner_id:i.owner_id,visibility:i.visibility,...i.data}));}
function rawById(id){return state.items.find(i=>i.id===id)}
function q(arr,fields){const v=state.q.toLowerCase();return !v?arr:arr.filter(x=>fields.some(f=>String(x[f]||'').toLowerCase().includes(v)))}
function msg(m){state.message=m;setTimeout(()=>{state.message='';render()},6500);render()}
function body(){document.body.className=(state.mode==='dark'?'dark ':'')+state.theme}
async function init(){body();if(!sb){render();return}const {data:{session}}=await sb.auth.getSession();state.session=session;state.user=session?.user||null;sb.auth.onAuthStateChange((event,session)=>{state.session=session;state.user=session?.user||null;if(event==='PASSWORD_RECOVERY')state.recover=true;if(session&&!state.recover)loadAll();else render()});if(session)await loadAll();else render()}
async function loadAll(){if(!sb||!state.user)return render();state.loading=true;render();const [a,b]=await Promise.all([sb.from('marketing_items').select('*').order('created_at',{ascending:false}),sb.from('marketing_profiles').select('*').order('created_at',{ascending:true})]);if(a.error)state.message='Błąd ładowania: '+a.error.message;state.items=a.data||[];state.profiles=b.data||[];state.loading=false;render()}
function render(){body();root.innerHTML=!sb?setupScreen():state.recover?resetPasswordScreen():state.user?appScreen():loginScreen();bind()}
function setupScreen(){return `<div class="login"><div class="log"><div class="hero"><div class="brand"><b class="mark">M</b><span>Marketing Hub</span></div><h1>Podłącz Supabase</h1><p>Wklej URL projektu i publishable/anon key. Dane będą wspólne, a prywatne notatki zabezpieczone przez RLS.</p></div><div class="form"><h2>Konfiguracja</h2><input id="cfgUrl" class="inp" placeholder="SUPABASE_URL"><input id="cfgKey" class="inp" placeholder="SUPABASE_ANON_KEY / publishable key"><input id="cfgDomain" class="inp" value="${esc(CONFIG.allowedDomain)}" placeholder="Domena, np. felg.app"><button id="saveCfg" class="btn">Zapisz konfigurację</button><p class="hint">Najpierw uruchom SQL z pliku <b>supabase/schema.sql</b>.</p></div></div></div>`}
function loginScreen(){const cls=state.message.toLowerCase().includes('błąd')||state.message.toLowerCase().includes('invalid')||state.message.toLowerCase().includes('error')?'err':'okbox';return `<div class="login"><div class="log"><div class="hero"><div class="brand"><b class="mark">M</b><span>Marketing Hub</span></div><h1>Logowanie do marketingu</h1><p>Normalne logowanie hasłem, tworzenie konta z potwierdzeniem maila i odzyskiwanie hasła.</p><p>Dostęp tylko dla adresów @${esc(CONFIG.allowedDomain)}.</p></div><div class="form"><div class="auth-tabs"><button class="btn sec ${state.authMode==='login'?'on':''}" data-auth="login">Zaloguj</button><button class="btn sec ${state.authMode==='signup'?'on':''}" data-auth="signup">Utwórz konto</button><button class="btn sec ${state.authMode==='reset'?'on':''}" data-auth="reset">Reset</button></div><h2>${state.authMode==='login'?'Zaloguj hasłem':state.authMode==='signup'?'Utwórz konto':'Odzyskaj hasło'}</h2>${state.message?`<div class="${cls}">${esc(state.message)}</div>`:''}<input id="email" class="inp" value="malgorzata.sliwa@felg.app" placeholder="e-mail firmowy">${state.authMode!=='reset'?'<input id="password" class="inp" type="password" placeholder="hasło, min. 6 znaków">':''}${state.authMode==='signup'?'<input id="fullName" class="inp" placeholder="imię i nazwisko">':''}<button id="authAction" class="btn">${state.authMode==='login'?'Zaloguj':state.authMode==='signup'?'Utwórz konto i wyślij potwierdzenie':'Wyślij link resetu hasła'}</button><p class="hint">Przy tworzeniu konta Supabase wyśle mail z potwierdzeniem. Po potwierdzeniu możesz logować się hasłem. Reset hasła wysyła link, po którym ustawisz nowe hasło.</p></div></div></div>`}
function resetPasswordScreen(){return `<div class="login"><div class="log"><div class="hero"><div class="brand"><b class="mark">M</b><span>Marketing Hub</span></div><h1>Ustaw nowe hasło</h1><p>Wpisz nowe hasło do konta.</p></div><div class="form"><h2>Nowe hasło</h2>${state.message?`<div class="okbox">${esc(state.message)}</div>`:''}<input id="newPassword" class="inp" type="password" placeholder="nowe hasło, min. 6 znaków"><button id="savePassword" class="btn">Zapisz nowe hasło</button></div></div></div>`}
function appScreen(){const p=state.profiles.find(x=>x.id===state.user.id);return `<div class="app"><aside class="side"><div class="brand"><b class="mark">M</b><span>Marketing Hub<br><small class="hint">Supabase online</small></span></div><div class="prof"><div class="av">${esc((p?.full_name||state.user.email||'G')[0]).toUpperCase()}</div><div><b>${esc(p?.full_name||'Gosia')}</b><br><small class="hint">${esc(state.user.email)}</small></div></div><div class="tabs"><button class="tab ${state.panel==='Ogólny'?'on':''}" data-panel="Ogólny">Ogólny</button><button class="tab ${state.panel==='Social'?'on':''}" data-panel="Social">Social</button><button class="tab ${state.panel==='Kreacje'?'on':''}" data-panel="Kreacje">Kreacje</button></div><nav class="nav">${Object.keys(labels).map(k=>`<button data-v="${k}" class="${state.view===k?'on':''}"><b>${labels[k].split(' ')[0]}</b><span>${labels[k].slice(2)}</span></button>`).join('')}</nav></aside><main class="main"><div class="top"><input id="q" class="inp" placeholder="Szukaj" value="${esc(state.q)}"><button class="btn" onclick="openModal('task')">+ Utwórz</button><button class="btn sec" onclick="loadAll()">Odśwież</button><button id="logout" class="btn sec">Wyloguj</button></div>${state.message?`<div class="okbox">${esc(state.message)}</div><br>`:''}${viewHtml()}</main></div>${modal()}${state.loading?'<div class="loader">Synchronizacja...</div>':''}`}
function T(a,b,c=''){return `<div class="title"><div><h1>${a}</h1><p class="hint">${b}</p></div>${c}</div>`}
function item(a,b,c=''){return `<div class="item"><div><h4>${esc(a)}</h4><p>${esc(b)}</p></div>${c}</div>`}
function act(id){return `<button class="btn sm del" onclick="removeItem('${id}')">Usuń</button>`}
function cards(arr,html){return `<div class="grid c2">${arr.map(x=>`<div class="card">${html(x)}</div>`).join('')||'<div class="card">Brak danych.</div>'}</div>`}
function viewHtml(){return({dash,cal,projects,tasks,social,creative,events,partners,materials,finance,checks,notes,reports,settings}[state.view]||dash)()}
function dash(){const tasks=byType('task'),events=byType('event'),partners=byType('partner'),finance=byType('finance'),cost=finance.reduce((a,b)=>a+(+b.amount||0),0);return T('Dashboard','Wspólna przestrzeń marketingu. Prywatne notatki widzi tylko właściciel.')+`<div class="grid c4"><div class="card metric"><small>Zadania</small><br><b>${tasks.length}</b></div><div class="card metric"><small>Wydarzenia</small><br><b>${events.length}</b></div><div class="card metric"><small>Partnerzy</small><br><b>${partners.length}</b></div><div class="card metric"><small>Koszty</small><br><b>${cost} zł</b></div></div><div class="grid c3" style="margin-top:14px"><div class="card"><h2>Priorytety</h2>${q(tasks,['title','status','panel']).slice(0,7).map(t=>item(t.title,`${t.status} · ${t.prio||'Normalny'} · ${t.due||''}`,act(t.id))).join('')||'<p class="hint">Brak zadań.</p>'}</div><div class="card"><h2>Wydarzenia</h2>${events.slice(0,7).map(e=>item(e.name,`${e.type} · ${e.date}`,act(e.id))).join('')||'<p class="hint">Brak wydarzeń.</p>'}</div><div class="card"><h2>Szybkie akcje</h2><button class="btn sec" onclick="openModal('social')">Post</button> <button class="btn sec" onclick="openModal('creative')">Brief</button> <button class="btn sec" onclick="openModal('note')">Notatka</button><hr><button class="btn" onclick="seedDemo()">Dodaj dane startowe</button></div></div>`}
function cal(){const events=byType('event'),posts=byType('social');return T('Kalendarz','Wszystkie działania marketingowe.',`<button class="btn" onclick="openModal('event')">+ Wydarzenie</button>`)+`<div class="card"><div class="cal">${Array.from({length:28},(_,i)=>i+1).map(d=>{let date='2026-07-'+String(d).padStart(2,'0'),ev=events.filter(x=>x.date===date).concat(posts.filter(x=>x.date===date).map(x=>({name:x.title,type:x.channel})));return `<div class="day"><b>${d}</b>${ev.map(x=>`<div class="pill">${esc(x.type)}: ${esc(x.name)}</div>`).join('')}</div>`}).join('')}</div></div>`}
function projects(){const arr=q(byType('project'),['name','status','desc','type']);return T('Projekty i kampanie','Cele, terminy, statusy i budżety.',`<button class="btn" onclick="openModal('project')">+ Projekt</button>`)+cards(arr,p=>`<span class="chip">${esc(p.type||'projekt')}</span><h2>${esc(p.name)}</h2><p>${esc(p.desc||'')}</p><p><b>${esc(p.status||'Planowanie')}</b> · ${esc(p.due||'')} · ${esc(p.budget||0)} zł</p>${act(p.id)}`)}
function tasks(){const arr=q(byType('task'),['title','status','panel','prio']);const cols=['Do zrobienia','W trakcie','Do sprawdzenia','Gotowe'];return T('Zadania','Kanban z zapisem w Supabase.',`<button class="btn" onclick="openModal('task')">+ Zadanie</button>`)+`<div class="kanban">${cols.map(c=>`<div class="col" ondragover="event.preventDefault()" ondrop="dropTask(event,'${c}')"><h3>${c}</h3>${arr.filter(t=>t.status===c).map(t=>`<div class="task" draggable="true" ondragstart="dragTask(event,'${t.id}')"><b>${esc(t.title)}</b><p class="hint">${esc(t.prio||'Normalny')} · ${esc(t.due||'')} · ${esc(t.panel||'Ogólny')}</p>${act(t.id)}</div>`).join('')}</div>`).join('')}</div>`}
function social(){const arr=q(byType('social'),['title','channel','status']);return T('Social Media','Panel social media w tej samej aplikacji.',`<button class="btn" onclick="openModal('social')">+ Post</button>`)+`<div class="grid c3"><div class="card"><h2>Plan publikacji</h2>${arr.map(x=>item(x.title,`${x.channel} · ${x.date} · ${x.status}`,act(x.id))).join('')||'<p class="hint">Brak postów.</p>'}</div><div class="card"><h2>UTM Builder</h2><input id="u" class="inp" placeholder="URL"><br><br><input id="src" class="inp" placeholder="source"><br><br><input id="camp" class="inp" placeholder="campaign"><br><br><button class="btn" onclick="utm()">Generuj</button><p id="uo" class="hint"></p></div><div class="card"><h2>Pomysły</h2>${['Koszt pustego fotela','5 automatyzacji recepcji','Case study'].map(x=>item(x,'pomysł contentowy')).join('')}</div></div>`}
function creative(){const arr=q(byType('creative'),['name','format','status']);return T('Kreacje i grafiki','Briefy, formaty i statusy.',`<button class="btn" onclick="openModal('creative')">+ Brief</button>`)+cards(arr,x=>`<span class="chip">${esc(x.status||'Brief')}</span><h2>${esc(x.name)}</h2><p>${esc(x.format||'')}</p><p class="hint">Deadline ${esc(x.due||'')}</p>${act(x.id)}`)}
function events(){const arr=q(byType('event'),['name','type','status']);const first=byType('template')[0];return T('Wydarzenia','Webinary, targi, eventy, spotkania.',`<button class="btn" onclick="openModal('event')">+ Wydarzenie</button>`)+cards(arr,x=>`<span class="chip">${esc(x.type)}</span><h2>${esc(x.name)}</h2><p>${esc(x.date)} · ${esc(x.status)}</p>${first?`<button class="btn sm sec" onclick="useTemplate('${first.id}')">Przypisz checklistę</button>`:''} ${act(x.id)}`)}
function partners(){const arr=q(byType('partner'),['name','type','person','notes']);return T('Partnerzy','Bez klientów: wykonawcy, dostawcy, media, organizatorzy.',`<button class="btn" onclick="openModal('partner')">+ Partner</button>`)+`<div class="card">${arr.map(p=>item(p.name,`${p.type} · ${p.person||''} · ${p.email||''}`,act(p.id))).join('')||'<p class="hint">Brak partnerów.</p>'}</div>`}
function materials(){const files=byType('file'),links=byType('dropbox'),wh=byType('warehouse');return T('Materiały i magazyn','Upload/download do Supabase Storage, Dropbox oraz magazyn Biuro/Garaż.',`<button class="btn" onclick="openModal('warehouse')">+ Materiał</button>`)+`<div class="grid c2"><div class="card"><h2>Pliki</h2><div id="drop" class="drop">Przeciągnij pliki albo kliknij<input id="file" type="file" multiple hidden></div>${files.map(f=>item(f.name,`${Math.round((f.size||0)/1024)} KB`,`<button class="btn sm sec" onclick="downloadFile('${f.id}')">Pobierz</button> ${act(f.id)}`)).join('')||'<p class="hint">Brak plików.</p>'}</div><div class="card"><h2>Dropbox</h2>${links.map(d=>item(d.name,d.cat,`<a class="btn sm sec" href="${esc(d.url)}" target="_blank">Otwórz</a> ${act(d.id)}`)).join('')||'<p class="hint">Brak linków.</p>'}<button class="btn sec" onclick="openModal('dropbox')">+ Link</button></div></div><div class="grid c2" style="margin-top:14px"><div class="card"><h2>Biuro</h2>${wh.filter(w=>w.place==='Biuro').map(w=>item(w.name,`${w.cat} · min. ${w.min}`,`<span class="chip ${(+w.qty<=+w.min)?'warn':'ok'}">${w.qty} szt.</span> ${act(w.id)}`)).join('')||'<p class="hint">Pusto.</p>'}</div><div class="card"><h2>Garaż</h2>${wh.filter(w=>w.place==='Garaż').map(w=>item(w.name,`${w.cat} · min. ${w.min}`,`<span class="chip ${(+w.qty<=+w.min)?'warn':'ok'}">${w.qty} szt.</span> ${act(w.id)}`)).join('')||'<p class="hint">Pusto.</p>'}</div></div>`}
function finance(){const arr=byType('finance');return T('Finanse','Faktury, koszty, narzędzia płatne i subskrypcje.',`<button class="btn" onclick="openModal('finance')">+ Koszt</button>`)+`<div class="grid c3"><div class="card"><h2>Do opłacenia</h2>${arr.filter(x=>x.status==='Do opłacenia').map(x=>item(x.name,`${x.type} · ${x.due}`,`<b>${x.amount} zł</b> ${act(x.id)}`)).join('')||'<p class="hint">Brak.</p>'}</div><div class="card"><h2>Subskrypcje</h2>${arr.filter(x=>x.status==='Subskrypcja').map(x=>item(x.name,`${x.type} · ${x.due}`,`<b>${x.amount} zł</b> ${act(x.id)}`)).join('')||'<p class="hint">Brak.</p>'}</div><div class="card"><h2>Narzędzia</h2>${arr.filter(x=>String(x.type).includes('Narzędzie')).map(x=>item(x.name,x.status,`<b>${x.amount} zł</b> ${act(x.id)}`)).join('')||'<p class="hint">Brak.</p>'}</div></div>`}
function checks(){const templates=byType('template'),assigned=byType('assigned_checklist');return T('Checklisty','Szablony można przypisywać i modyfikować.',`<button class="btn" onclick="openModal('template')">+ Szablon</button>`)+`<div class="grid c2"><div class="card"><h2>Szablony</h2>${templates.map(t=>item(t.name,(t.items||[]).length+' punktów',`<button class="btn sm sec" onclick="useTemplate('${t.id}')">Użyj</button> ${act(t.id)}`)).join('')||'<p class="hint">Brak.</p>'}</div><div class="card"><h2>Przypisane</h2>${assigned.map(c=>`<h3>${esc(c.name)} ${act(c.id)}</h3>${(c.items||[]).map((x,i)=>`<div class="item"><label><input type="checkbox" ${x.d?'checked':''} onchange="toggleCheck('${c.id}',${i})"> ${esc(x.t)}</label><button class="btn sm sec" onclick="taskFromCheck('${c.id}',${i})">Zadanie</button></div>`).join('')}`).join('')||'<p class="hint">Brak przypisanych checklist.</p>'}</div></div>`}
function notes(){const arr=byType('note');return T('Notatki wizualne','Prywatne notatki są filtrowane przez Supabase RLS.',`<button class="btn" onclick="openModal('note')">+ Notatka</button>`)+`<div class="card"><div class="board">${arr.map(n=>`<div class="note ${esc(n.c||'pink')}" data-n="${n.id}" style="left:${+n.x||70}px;top:${+n.y||70}px"><b>${esc(n.title)}</b><p>${esc(n.body)}</p><small>${n.visibility==='private'?'🔒 prywatna':'👥 wspólna'}</small><br>${act(n.id)}</div>`).join('')}</div></div>`}
function reports(){return T('Raporty','Statystyki i eksport danych.')+`<div class="grid c4"><div class="card metric"><small>Zadania</small><br><b>${byType('task').length}</b></div><div class="card metric"><small>Posty</small><br><b>${byType('social').length}</b></div><div class="card metric"><small>Kreacje</small><br><b>${byType('creative').length}</b></div><div class="card metric"><small>Magazyn</small><br><b>${byType('warehouse').reduce((a,b)=>a+(+b.qty||0),0)}</b></div></div><div class="card" style="margin-top:14px"><button class="btn" onclick="exportData()">Eksport JSON</button></div>`}
function settings(){return T('Ustawienia','Zespół, motywy, integracje i Supabase.')+`<div class="grid c2"><div class="card"><h2>Zespół</h2>${state.profiles.map(u=>item(u.full_name||u.email,`${u.email} · ${u.role}`,u.id===state.user.id?'<span class="chip">Ty</span>':'<span class="chip ok">ma dostęp</span>')).join('')||'<p class="hint">Brak profili.</p>'}</div><div class="card"><h2>Wygląd</h2><div class="grid c2">${['ocean','rose','forest','violet'].map(t=>`<button class="sw ${t}" onclick="theme('${t}')"></button>`).join('')}</div><br><button class="btn sec" onclick="mode()">Jasny/ciemny</button></div><div class="card"><h2>Integracje</h2>${['Dropbox','Google Calendar','Outlook','Bitrix/CRM','Meta Ads','Google Ads','Slack/Teams','SMTP','Księgowość'].map(x=>item(x,'do podłączenia przez backend/API','<span class="chip warn">plan</span>')).join('')}</div><div class="card"><h2>Supabase</h2><p><b>Projekt:</b> ${esc(CONFIG.supabaseUrl||'brak')}</p><button class="btn sec" onclick="clearConfig()">Zmień konfigurację</button></div></div>`}
function modal(){return `<div id="mo" class="modal"><div class="box"><div style="display:flex;justify-content:space-between;gap:12px"><h2 id="mt">Dodaj</h2><button class="btn sec" onclick="closeModal()">✕</button></div><div id="mb"></div></div></div>`}
function openModal(k){$('mo').classList.add('on');$('mt').textContent='Dodaj: '+k;const f={task:['title:Nazwa','due:Termin','prio:Priorytet','panel:Panel'],project:['name:Nazwa','type:Typ','status:Status','due:Deadline','budget:Budżet','desc:Opis'],event:['name:Nazwa','type:Typ','date:Data','status:Status'],partner:['name:Nazwa','type:Typ','person:Osoba','email:E-mail','phone:Telefon','notes:Notatki'],social:['title:Tytuł','channel:Kanał','status:Status','date:Data'],creative:['name:Nazwa','format:Format','status:Status','due:Deadline'],warehouse:['name:Nazwa','place:Biuro/Garaż','qty:Ilość','min:Minimum','cat:Kategoria'],finance:['name:Nazwa','amount:Kwota','status:Status','due:Termin','type:Typ'],dropbox:['name:Nazwa','url:Link','cat:Kategoria']};if(k==='note')return $('mb').innerHTML=`<input id="f_title" class="inp" placeholder="Tytuł"><br><br><textarea id="f_body" class="inp" placeholder="Treść"></textarea><br><br><select id="f_visibility" class="inp"><option value="private">Prywatna — tylko ja</option><option value="team">Wspólna — marketing</option></select><br><br><button class="btn" onclick="addItem('note')">Zapisz</button>`;if(k==='template')return $('mb').innerHTML=`<input id="f_name" class="inp" placeholder="Nazwa"><br><br><textarea id="f_items" class="inp" placeholder="Punkty, każdy w nowej linii"></textarea><br><br><button class="btn" onclick="addItem('template')">Zapisz</button>`;$('mb').innerHTML=`<div class="fg">${(f[k]||f.task).map(x=>{let a=x.split(':');return `<label><small>${a[1]}</small><input class="inp" id="f_${a[0]}"></label>`}).join('')}<button class="btn full" onclick="addItem('${k}')">Zapisz</button></div>`}
function closeModal(){$('mo')?.classList.remove('on')}const val=x=>$('f_'+x)?.value||'';
async function addItem(k){let type=typeMap[k+'s']||k,visibility='team',data={};if(k==='task')data={title:val('title'),due:val('due')||today(),prio:val('prio')||'Normalny',status:'Do zrobienia',panel:val('panel')||state.panel};if(k==='project')data={name:val('name'),type:val('type')||'projekt',status:val('status')||'Planowanie',due:val('due')||today(),budget:+val('budget')||0,desc:val('desc')};if(k==='event')data={name:val('name'),type:val('type')||'Event',date:val('date')||today(),status:val('status')||'Plan'};if(k==='partner')data={name:val('name'),type:val('type')||'Dostawca',person:val('person'),email:val('email'),phone:val('phone'),notes:val('notes')};if(k==='social')data={title:val('title'),channel:val('channel')||'LinkedIn',status:val('status')||'Draft',date:val('date')||today()};if(k==='creative')data={name:val('name'),format:val('format'),status:val('status')||'Brief',due:val('due')||today()};if(k==='warehouse')data={name:val('name'),place:val('place')==='Garaż'?'Garaż':'Biuro',qty:+val('qty')||0,min:+val('min')||0,cat:val('cat')};if(k==='finance')data={name:val('name'),amount:+val('amount')||0,status:val('status')||'Do opłacenia',due:val('due')||today(),type:val('type')||'Koszt'};if(k==='dropbox')data={name:val('name'),url:val('url'),cat:val('cat')};if(k==='template')data={name:val('name'),items:val('items').split('\n').filter(Boolean)};if(k==='note'){type='note';visibility=val('visibility');data={title:val('title'),body:val('body'),x:80+Math.random()*260,y:70+Math.random()*230,c:'pink',visibility}}await insertItem(type,data,visibility);closeModal();await loadAll()}
async function insertItem(type,data,visibility='team'){state.loading=true;render();const {error}=await sb.from('marketing_items').insert({type,data,visibility,owner_id:state.user.id});state.loading=false;if(error)msg(error.message)}
async function updateItem(id,data,visibility){const row=rawById(id);if(!row)return;const {error}=await sb.from('marketing_items').update({data:Object.assign({},row.data,data),visibility:visibility||row.visibility}).eq('id',id);if(error)msg(error.message);await loadAll()}
async function removeItem(id){if(!confirm('Usunąć element?'))return;const row=rawById(id);if(row?.type==='file'&&row.data.path)await sb.storage.from('marketing-files').remove([row.data.path]);const {error}=await sb.from('marketing_items').delete().eq('id',id);if(error)msg(error.message);await loadAll()}
async function seedDemo(){state.loading=true;render();const rows=seedItems.map(x=>({type:x.type,visibility:x.visibility,data:x.data,owner_id:state.user.id}));const {error}=await sb.from('marketing_items').insert(rows);state.loading=false;if(error)msg(error.message);await loadAll()}
async function useTemplate(id){const t=rawById(id);if(!t)return;await insertItem('assigned_checklist',{name:(t.data.name||'Checklista')+' — kopia',items:(t.data.items||[]).map(x=>({t:x,d:false}))},'team');await loadAll()}
async function toggleCheck(id,i){const row=rawById(id),items=[...(row.data.items||[])];items[i].d=!items[i].d;await updateItem(id,{items})}
async function taskFromCheck(id,i){const row=rawById(id),it=row.data.items[i];await insertItem('task',{title:it.t,status:'Do zrobienia',prio:'Normalny',due:today(),panel:'Ogólny'},'team');await loadAll()}
function dragTask(e,id){e.dataTransfer.setData('id',id)}async function dropTask(e,status){await updateItem(e.dataTransfer.getData('id'),{status})}
function bind(){document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{state.view=b.dataset.v;render()});document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{state.panel=b.dataset.panel;render()});document.querySelectorAll('[data-auth]').forEach(b=>b.onclick=()=>{state.authMode=b.dataset.auth;state.message='';render()});if($('saveCfg'))$('saveCfg').onclick=()=>{localStorage.setItem('mh-config',JSON.stringify({supabaseUrl:$('cfgUrl').value.trim(),supabaseAnonKey:$('cfgKey').value.trim(),allowedDomain:$('cfgDomain').value.trim()||'felg.app'}));location.reload()};if($('authAction'))$('authAction').onclick=authAction;if($('savePassword'))$('savePassword').onclick=saveNewPassword;if($('logout'))$('logout').onclick=async()=>{await sb.auth.signOut()};if($('q'))$('q').oninput=e=>{state.q=e.target.value;render()};bindDrop();bindNotes()}
function domainOk(email){return email.toLowerCase().endsWith('@'+CONFIG.allowedDomain.toLowerCase())}
async function authAction(){const email=$('email').value.trim(),password=$('password')?.value||'',fullName=$('fullName')?.value||'';if(!domainOk(email))return msg('Dostęp tylko dla @'+CONFIG.allowedDomain);if(state.authMode==='login'){const {error}=await sb.auth.signInWithPassword({email,password});if(error)return msg(error.message.includes('Email not confirmed')?'Najpierw potwierdź e-mail z wiadomości od Supabase.':error.message);return}if(state.authMode==='signup'){if(password.length<6)return msg('Hasło musi mieć minimum 6 znaków.');const {error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname,data:{full_name:fullName||email.split('@')[0]}}});return msg(error?error.message:'Konto utworzone. Sprawdź e-mail i kliknij potwierdzenie, potem zaloguj się hasłem.')}if(state.authMode==='reset'){const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});return msg(error?error.message:'Wysłano link do ustawienia nowego hasła.')}}
async function saveNewPassword(){const password=$('newPassword').value;if(password.length<6)return msg('Hasło musi mieć minimum 6 znaków.');const {error}=await sb.auth.updateUser({password});if(error)return msg(error.message);state.recover=false;msg('Hasło zmienione. Możesz korzystać z aplikacji.');await loadAll()}
function bindDrop(){const d=$('drop'),f=$('file');if(!d)return;d.onclick=()=>f.click();d.ondragover=e=>e.preventDefault();d.ondrop=e=>{e.preventDefault();uploadFiles(e.dataTransfer.files)};f.onchange=e=>uploadFiles(e.target.files)}
async function uploadFiles(list){for(const file of [...list]){const path=`${state.user.id}/${Date.now()}-${file.name}`;state.loading=true;render();const up=await sb.storage.from('marketing-files').upload(path,file,{upsert:false});state.loading=false;if(up.error){msg(up.error.message);continue}await insertItem('file',{name:file.name,size:file.size,path,mime:file.type},'team')}await loadAll()}
async function downloadFile(id){const row=rawById(id);if(!row)return;const {data,error}=await sb.storage.from('marketing-files').createSignedUrl(row.data.path,60);if(error)return msg(error.message);const a=document.createElement('a');a.href=data.signedUrl;a.download=row.data.name;a.click()}
function bindNotes(){document.querySelectorAll('.note').forEach(el=>{let ox,oy,id=el.dataset.n;el.onpointerdown=e=>{el.setPointerCapture(e.pointerId);ox=e.clientX-el.offsetLeft;oy=e.clientY-el.offsetTop};el.onpointermove=e=>{if(!el.hasPointerCapture(e.pointerId))return;el.style.left=e.clientX-ox+'px';el.style.top=e.clientY-oy+'px'};el.onpointerup=async e=>{try{el.releasePointerCapture(e.pointerId)}catch(_){};await updateItem(id,{x:parseInt(el.style.left),y:parseInt(el.style.top)})}})}
function utm(){const u=$('u').value||'https://felg.app',src=$('src').value||'social',camp=$('camp').value||'kampania';$('uo').textContent=u+(u.includes('?')?'&':'?')+'utm_source='+encodeURIComponent(src)+'&utm_medium=social&utm_campaign='+encodeURIComponent(camp)}
function theme(t){state.theme=t;localStorage.setItem('mh-theme',t);render()}function mode(){state.mode=state.mode==='dark'?'light':'dark';localStorage.setItem('mh-mode',state.mode);render()}function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({items:state.items,profiles:state.profiles},null,2)],{type:'application/json'}));a.download='marketing-hub-export.json';a.click()}function clearConfig(){if(confirm('Usunąć lokalną konfigurację Supabase?')){localStorage.removeItem('mh-config');location.reload()}}
init();
