import './styles.css';

const root = document.getElementById('root');
const modal = document.getElementById('modal');
const ENV = {
  url: import.meta.env.VITE_SUPABASE_URL || '',
  key: import.meta.env.VITE_SUPABASE_ANON_KEY || '',
  domain: import.meta.env.VITE_ALLOWED_DOMAIN || 'felg.app',
};
let cfg = { supabaseUrl: ENV.url, supabaseAnonKey: ENV.key, allowedDomain: ENV.domain };
try {
  const local = JSON.parse(localStorage.getItem('mh-config') || '{}');
  cfg = { ...cfg, ...Object.fromEntries(Object.entries(local).filter(([,v]) => v)) };
} catch (_) {}
let sb = cfg.supabaseUrl && cfg.supabaseAnonKey && window.supabase ? window.supabase.createClient(cfg.supabaseUrl, cfg.supabaseAnonKey) : null;
const now = new Date();
const S = { user:null, items:[], view:'dashboard', mode:'login', q:'', msg:'', y:now.getFullYear(), m:now.getMonth(), filter:'all', selected:[] };
const modules = { dashboard:'🏠 Dashboard', calendar:'📅 Kalendarz', tasks:'✅ Zadania', projects:'📁 Projekty i kampanie', events:'🎤 Wydarzenia', social:'📱 Social Media', creative:'🎨 Kreacje', partners:'🤝 Partnerzy', files:'🗂️ Pliki', warehouse:'📦 Magazyn', finance:'💳 Faktury i koszty', checks:'☑️ Checklisty', notes:'📝 Notatki', reports:'📊 Raporty i eksport', sharing:'🔗 Udostępnianie', integrations:'🔌 Integracje', settings:'⚙️ Ustawienia' };
const map = { tasks:'task', projects:'project', events:'event', social:'social', creative:'creative', partners:'partner', warehouse:'warehouse', finance:'finance', checks:'template', notes:'note' };
const fields = {
  task:[['title','Nazwa zadania'],['status','Status','select','Do zrobienia|W trakcie|Do sprawdzenia|Gotowe'],['priority','Priorytet','select','Niski|Normalny|Wysoki|Pilne'],['due','Termin','date'],['owner','Odpowiedzialny'],['description','Opis','textarea']],
  project:[['name','Nazwa'],['kind','Typ','select','Projekt|Kampania'],['status','Status','select','Pomysł|Planowanie|W trakcie|Do akceptu|Zakończone'],['budget','Budżet','number'],['due','Deadline','date'],['description','Opis szczegółowy','textarea']],
  event:[['name','Nazwa działania w kalendarzu'],['kind','Typ','select','Webinar|Targi|Event|Spotkanie|Deadline|Kampania|Social Media|Inne'],['calendar_bucket','Widok kalendarza','select','Ogólny|Social Media|Wydarzenia|Webinary|Targi|Kampanie|Deadline’y'],['date','Data','date'],['time','Godzina startu'],['end_time','Godzina końca'],['status','Status','select','Pomysł|Plan|W przygotowaniu|Do akceptu|Gotowe|Po wydarzeniu|Anulowane'],['owner','Osoba odpowiedzialna'],['host','Prowadzący / organizator'],['place','Miejsce / link do spotkania'],['registration_link','Link do zapisów / landing'],['project','Powiązany projekt lub kampania'],['budget','Budżet / koszt planowany','number'],['participants','Uczestnicy / grupa docelowa'],['materials','Materiały potrzebne','textarea'],['checklist','Checklista / rzeczy do dopilnowania','textarea'],['notes','Notatki organizacyjne','textarea'],['description','Opis szczegółowy','textarea']],
  social:[['title','Tytuł'],['channel','Kanał','select','LinkedIn|Facebook|Instagram|TikTok|YouTube|Newsletter'],['date','Data publikacji','date'],['status','Status','select','Pomysł|Draft|Do akceptu|Zaplanowane|Opublikowane'],['copy','Treść posta','textarea']],
  creative:[['name','Nazwa'],['format','Format'],['status','Status','select','Brief|W trakcie|Do akceptu|Poprawki|Gotowe'],['due','Deadline','date'],['brief','Brief','textarea']],
  partner:[['name','Nazwa'],['kind','Typ','select','Wykonawca|Dostawca|Media|Organizator|Partner biznesowy|Inne'],['person','Osoba kontaktowa'],['email','E-mail'],['phone','Telefon'],['notes','Notatki','textarea']],
  warehouse:[['name','Nazwa'],['place','Miejsce','select','Biuro|Garaż'],['qty','Ilość','number'],['min','Minimum','number'],['category','Kategoria'],['location','Lokalizacja'],['notes','Opis','textarea']],
  finance:[['name','Nazwa faktury / kosztu / narzędzia'],['marketing_for','Za co jest koszt?','textarea'],['kind','Typ kosztu','select','Faktura marketingowa|Koszt kampanii|Subskrypcja|Narzędzie płatne|Reklama płatna|Usługa zewnętrzna|Druk / materiały|Inne'],['tool_name','Nazwa narzędzia / usługi'],['supplier','Dostawca / wykonawca'],['amount','Kwota','number'],['currency','Waluta','select','PLN|EUR|USD|GBP'],['status','Status płatności','select','Do opłacenia|Opłacone|Automatycznie pobierane|Subskrypcja aktywna|Wstrzymane|Anulowane'],['due','Do kiedy opłacić','date'],['invoice_date','Data faktury','date'],['invoice_number','Numer faktury'],['billing_period','Okres rozliczenia','select','Jednorazowo|Miesięcznie|Rocznie|Kwartalnie|Inny'],['is_subscription','Czy to subskrypcja?','select','Nie|Tak'],['auto_charge','Czy schodzi automatycznie z karty?','select','Nie|Tak'],['payment_method','Metoda płatności','select','Przelew|Karta firmowa|Automatycznie z karty|PayPal|Inne'],['card_owner','Karta / osoba odpowiedzialna'],['project','Powiązany projekt / kampania'],['owner','Osoba odpowiedzialna za koszt'],['notes','Notatki / uwagi księgowe','textarea']],
  template:[['name','Nazwa'],['items','Punkty checklisty - każdy w nowej linii','textarea']],
  note:[['title','Tytuł'],['body','Treść','textarea']],
  share:[['name','Nazwa udostępnienia'],['scope','Co udostępnić','select','Dashboard|Kalendarz|Projekty|Wydarzenia|Social Media|Pliki|Raport'],['guest_email','E-mail gościa'],['expires','Ważne do','date'],['permission','Uprawnienia','select','Tylko podgląd|Komentowanie|Pobieranie plików'],['notes','Notatka dla gościa','textarea']]
};
const esc = x => String(x ?? '').replace(/[&<>]/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
const toast = t => { const d=document.createElement('div'); d.className='toast'; d.textContent=t; document.body.appendChild(d); setTimeout(()=>d.remove(),5500); };
const type = t => S.items.filter(i=>i.type===t).map(i=>({id:i.id, visibility:i.visibility, owner_id:i.owner_id, ...(i.data||{})}));
const raw = id => S.items.find(i=>i.id===id);
const filtered = a => { const q=S.q.toLowerCase(); return q ? a.filter(x=>JSON.stringify(x).toLowerCase().includes(q)) : a; };
const visLabel = v => v==='private' ? '🔒 Prywatne' : '👥 Zespół';
const visClass = v => v==='private' ? 'private' : 'team';
async function init(){ if(!sb) return config(); const r=await sb.auth.getSession(); S.user=r.data.session?.user||null; sb.auth.onAuthStateChange((_,s)=>{ S.user=s?.user||null; S.user?load():authScreen(); }); S.user?load():authScreen(); }
async function load(){ const r=await sb.from('marketing_items').select('*').order('created_at',{ascending:false}); if(r.error){ toast('Błąd ładowania: '+r.error.message); S.items=[]; } else S.items=r.data||[]; S.selected=S.selected.filter(id=>S.items.some(i=>i.id===id)); app(); }
function config(){ root.innerHTML=`<div class="login"><div class="loginbox"><div class="hero"><h1>Marketing Hub</h1><p>Brakuje globalnej konfiguracji Supabase. Ustaw zmienne w Netlify albo wpisz awaryjnie tutaj.</p></div><div class="form"><input id="u" class="inp" placeholder="SUPABASE_URL"><input id="k" class="inp" placeholder="SUPABASE_ANON_KEY"><input id="d" class="inp" value="${esc(cfg.allowedDomain)}"><button id="save" class="btn">Zapisz lokalnie</button></div></div></div>`; document.getElementById('save').onclick=()=>{ localStorage.setItem('mh-config',JSON.stringify({supabaseUrl:u.value.trim(),supabaseAnonKey:k.value.trim(),allowedDomain:d.value.trim()||'felg.app'})); location.reload(); }; }
function authScreen(){ const title=S.mode==='login'?'Zaloguj':S.mode==='signup'?'Utwórz konto':'Reset hasła'; root.innerHTML=`<div class="login"><div class="loginbox"><div class="hero"><h1>Marketing Hub</h1><p>Dostęp tylko @${cfg.allowedDomain}</p></div><div class="form"><div class="tabs"><button class="btn sec ${S.mode==='login'?'on':''}" id="ml">Zaloguj</button><button class="btn sec ${S.mode==='signup'?'on':''}" id="ms">Utwórz</button><button class="btn sec ${S.mode==='reset'?'on':''}" id="mr">Reset</button></div>${S.msg?`<div class="msg">${esc(S.msg)}</div>`:''}<input id="email" class="inp" value="malgorzata.sliwa@felg.app"><input id="pass" class="inp" type="password" placeholder="hasło" style="${S.mode==='reset'?'display:none':''}"><button id="go" class="btn">${title}</button></div></div></div>`; ml.onclick=()=>{S.mode='login';authScreen()}; ms.onclick=()=>{S.mode='signup';authScreen()}; mr.onclick=()=>{S.mode='reset';authScreen()}; go.onclick=authGo; }
async function authGo(){ const email=document.getElementById('email').value.trim(), pass=document.getElementById('pass').value; if(!email.endsWith('@'+cfg.allowedDomain)){ S.msg='Dostęp tylko dla @'+cfg.allowedDomain; return authScreen(); } try{ if(S.mode==='login'){ const r=await sb.auth.signInWithPassword({email,password:pass}); if(r.error) throw r.error; S.user=r.data.user; await load(); } if(S.mode==='signup'){ const r=await sb.auth.signUp({email,password:pass,options:{emailRedirectTo:location.origin}}); if(r.error) throw r.error; S.msg='Konto utworzone. Potwierdź mail.'; authScreen(); } if(S.mode==='reset'){ const r=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin}); if(r.error) throw r.error; S.msg='Wysłano reset hasła.'; authScreen(); } } catch(e){ S.msg=e.message; authScreen(); } }
function app(){ const nav=Object.keys(modules).map(k=>`<button class="${S.view===k?'on':''}" data-view="${k}">${modules[k]}</button>`).join(''); root.innerHTML=`<div class="app"><aside class="side"><div class="brand">⚡ Marketing Hub</div><div class="user"><b>${esc(S.user.email)}</b><br><span class="hint">zalogowano</span></div><nav class="nav">${nav}</nav></aside><main class="main"><div class="top"><input id="search" class="inp" placeholder="Szukaj" value="${esc(S.q)}"><button class="btn" id="addTop">+ Dodaj</button><button class="btn sec" id="logout">Wyloguj</button></div>${screen()}</main></div>`; document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{S.view=b.dataset.view;S.selected=[];app();}); search.oninput=e=>{S.q=e.target.value;app();}; addTop.onclick=()=>openForm(defaultType()); logout.onclick=()=>sb.auth.signOut(); bindPage(); }
function defaultType(){ return S.view==='sharing'?'share':map[S.view]||'task'; }
function title(t,d,b=''){ return `<div class="title"><div><h1>${t}</h1><p class="hint">${d}</p></div>${b}</div>`; }
function screen(){ if(S.view==='dashboard')return dashboard(); if(S.view==='calendar')return calendar(); if(S.view==='warehouse')return warehouse(); if(S.view==='files')return files(); if(S.view==='settings')return settings(); if(S.view==='reports')return reports(); if(S.view==='sharing')return sharing(); if(S.view==='integrations')return integrations(); return list(defaultType(),modules[S.view]); }
function dashboard(){ const cost=type('finance').reduce((a,b)=>a+(+b.amount||0),0); return title('Dashboard','Podsumowanie realnych danych z aplikacji')+`<div class="grid g4"><div class="card metric">Zadania<br><b>${type('task').length}</b></div><div class="card metric">Projekty<br><b>${type('project').length}</b></div><div class="card metric">Wydarzenia<br><b>${type('event').length}</b></div><div class="card metric">Koszty<br><b>${cost} zł</b></div></div><div class="grid g2" style="margin-top:14px"><div class="card"><h2>Najbliższe terminy</h2>${items(type('task').filter(x=>x.due).slice(0,6).concat(type('event').filter(x=>x.date).slice(0,6)))}</div><div class="card"><h2>Widoczność</h2><p><span class="tag team">👥 Zespół</span> widzą wszyscy zalogowani z @${cfg.allowedDomain}</p><p><span class="tag private">🔒 Prywatne</span> widzi tylko autor wpisu</p></div></div>`; }
function list(t,label){ const arr=filtered(type(t)); return title(label,'Dodawanie, edycja, szczegóły i usuwanie.',`<button class="btn" data-add="${t}">+ Dodaj</button>`)+bulkBar()+`<div class="grid g2">${arr.map(card).join('')||'<div class="card">Brak danych.</div>'}</div>`; }
function bulkBar(){ return `<div class="bulk"><b>Zaznaczone: ${S.selected.length}</b><button class="btn sec small" id="selVisible">Zaznacz widoczne</button><button class="btn sec small" id="unselect">Odznacz</button><button class="btn danger small" id="bulkDel">Usuń zaznaczone</button></div>`; }
function card(x){ const n=x.name||x.title||'(bez nazwy)', s=x.status||x.kind||x.channel||x.date||x.due||x.email||x.scope||''; return `<div class="card"><div class="row"><input class="check" type="checkbox" ${S.selected.includes(x.id)?'checked':''} data-check="${x.id}"><span class="tag ${visClass(x.visibility)}">${visLabel(x.visibility)}</span></div><h2>${esc(n)}</h2><p class="hint">${esc(s)}</p><p>${esc((x.marketing_for||x.description||x.brief||x.notes||x.body||'').slice(0,180))}</p><button class="btn small sec" data-details="${x.id}">Szczegóły</button> <button class="btn small" data-edit="${x.id}">Edytuj</button> <button class="btn small danger" data-del="${x.id}">Usuń</button></div>`; }
function items(arr){ return arr.map(x=>`<div class="item"><b>${esc(x.name||x.title)}</b><p class="hint">${esc(x.date||x.due||x.status||'')} · <span class="tag ${visClass(x.visibility)}">${visLabel(x.visibility)}</span></p></div>`).join('')||'<p class="hint">Brak.</p>'; }
function bindPage(){ document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openForm(b.dataset.add)); document.querySelectorAll('[data-check]').forEach(c=>c.onchange=()=>toggleSelect(c.dataset.check)); document.querySelectorAll('[data-details]').forEach(b=>b.onclick=()=>details(b.dataset.details)); document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openForm(null,b.dataset.edit)); document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>removeItem(b.dataset.del)); const sv=document.getElementById('selVisible'), un=document.getElementById('unselect'), bd=document.getElementById('bulkDel'); if(sv)sv.onclick=()=>{ const arr=filtered(type(defaultType())); S.selected=[...new Set([...S.selected,...arr.map(x=>x.id)])]; app();}; if(un)un.onclick=()=>{S.selected=[];app();}; if(bd)bd.onclick=bulkDelete; const fi=document.getElementById('fileInput'); if(fi)fi.onchange=uploadFiles; }
function toggleSelect(id){ S.selected=S.selected.includes(id)?S.selected.filter(x=>x!==id):[...S.selected,id]; app(); }
async function bulkDelete(){ if(!S.selected.length)return toast('Nic nie zaznaczono'); if(!confirm('Usunąć zaznaczone elementy: '+S.selected.length+'?'))return; const r=await sb.from('marketing_items').delete().in('id',S.selected).select(); if(r.error)return toast('Błąd usuwania: '+r.error.message); S.selected=[]; await load(); toast('Usunięto zaznaczone'); }
function iso(y,m,d){return y+'-'+String(m+1).padStart(2,'0')+'-'+String(d).padStart(2,'0')} function monthName(){return new Date(S.y,S.m,1).toLocaleDateString('pl-PL',{month:'long',year:'numeric'})}
function calItems(){ let a=[]; type('event').forEach(x=>x.date&&a.push({...x,calDate:x.date,calType:(x.kind||'event').toLowerCase(),group:'events',label:x.kind||'Wydarzenie'})); type('social').forEach(x=>x.date&&a.push({...x,calDate:x.date,calType:'social',group:'social',label:x.channel||'SM'})); type('task').forEach(x=>x.due&&a.push({...x,calDate:x.due,calType:'deadline',group:'deadlines',label:'Deadline'})); type('project').forEach(x=>x.due&&a.push({...x,calDate:x.due,calType:'campaign',group:'campaigns',label:x.kind||'Kampania'})); type('creative').forEach(x=>x.due&&a.push({...x,calDate:x.due,calType:'deadline',group:'deadlines',label:'Kreacja'})); return a.filter(x=>S.filter==='all'||(S.filter==='webinars'?String(x.kind).toLowerCase()==='webinar':x.group===S.filter)); }
function calendar(){ const fs=[['all','Ogólny'],['social','Kalendarz SM'],['events','Wydarzenia'],['webinars','Webinary'],['campaigns','Kampanie'],['deadlines','Deadline’y']]; const first=new Date(S.y,S.m,1), days=new Date(S.y,S.m+1,0).getDate(), start=(first.getDay()+6)%7, today=new Date().toISOString().slice(0,10), ev=calItems(); let cells=[]; for(let i=0;i<start;i++)cells.push('<div class="day empty"></div>'); for(let d=1;d<=days;d++){ const date=iso(S.y,S.m,d), list=ev.filter(x=>x.calDate===date); cells.push(`<div class="day ${date===today?'today':''}"><div class="daynum"><span>${d}</span><button class="plus" data-caladd="${date}">+</button>${date===today?'<span class="tag">dziś</span>':''}</div>${list.map(x=>`<div class="ev ${esc(x.calType)}" data-details="${x.id}"><b>${esc(x.label)}</b> ${esc(x.name||x.title)}</div>`).join('')}</div>`);} setTimeout(bindCalendar,0); return title('Kalendarz marketingu','Plus na dniu dodaje element z gotową datą. Kliknięcie wpisu otwiera edycję/usuwanie.',`<button class="btn" data-add="event">+ Wydarzenie</button>`)+`<div class="card"><div class="caltools"><button class="btn sec" data-move="-12">« Rok</button><button class="btn sec" data-move="-1">‹ Miesiąc</button><button class="btn" id="todayBtn">Dzisiaj</button><button class="btn sec" data-move="1">Miesiąc ›</button><button class="btn sec" data-move="12">Rok »</button><h2 style="margin:0;text-transform:capitalize">${monthName()}</h2></div><div class="caltools">${fs.map(f=>`<button class="btn sec ${S.filter===f[0]?'on':''}" data-filter="${f[0]}">${f[1]}</button>`).join('')}</div><div class="cal"><div class="weekday">Pon</div><div class="weekday">Wt</div><div class="weekday">Śr</div><div class="weekday">Czw</div><div class="weekday">Pt</div><div class="weekday">Sob</div><div class="weekday">Nd</div>${cells.join('')}</div></div>`; }
function bindCalendar(){ document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const x=new Date(S.y,S.m+Number(b.dataset.move),1);S.y=x.getFullYear();S.m=x.getMonth();app();}); const t=document.getElementById('todayBtn'); if(t)t.onclick=()=>{const d=new Date();S.y=d.getFullYear();S.m=d.getMonth();app();}; document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{S.filter=b.dataset.filter;app();}); document.querySelectorAll('[data-caladd]').forEach(b=>b.onclick=()=>openCalAdd(b.dataset.caladd)); }
function openCalAdd(date){ modal.className='modal on'; modal.innerHTML=`<div class="box"><div class="row"><h2>Dodaj do kalendarza: ${date}</h2><button class="btn sec" id="closeM">✕</button></div><div class="grid g2"><button class="btn" data-caltype="event">Wydarzenie / webinar / targi</button><button class="btn" data-caltype="social">Post Social Media</button><button class="btn" data-caltype="task">Deadline zadania</button><button class="btn" data-caltype="project">Deadline kampanii</button><button class="btn" data-caltype="creative">Deadline kreacji</button></div></div>`; document.getElementById('closeM').onclick=closeM; document.querySelectorAll('[data-caltype]').forEach(b=>b.onclick=()=>openFormDate(b.dataset.caltype,date)); }
function openFormDate(t,date){ const data={}; if(['event','social'].includes(t))data.date=date; else data.due=date; openForm(t,null,data); }
function warehouse(){ const arr=filtered(type('warehouse')), b=arr.filter(x=>x.place!=='Garaż'), g=arr.filter(x=>x.place==='Garaż'); const col=a=>a.map(x=>`<div class="item"><div><b>${esc(x.name)}</b><p class="hint">${esc(x.category||'')} · ${x.qty||0} szt. · <span class="tag ${visClass(x.visibility)}">${visLabel(x.visibility)}</span></p></div><button class="btn small" data-edit="${x.id}">Edytuj</button> <button class="btn small danger" data-del="${x.id}">Usuń</button></div>`).join('')||'<p class="hint">Pusto.</p>'; return title('Magazyn','Biuro i Garaż',`<button class="btn" data-add="warehouse">+ Dodaj</button>`)+bulkBar()+`<div class="grid g2"><div class="card"><h2>Biuro</h2>${col(b)}</div><div class="card"><h2>Garaż</h2>${col(g)}</div></div>`; }
function files(){ const arr=type('file'); return title('Pliki','Upload i pobieranie plików')+bulkBar()+`<div class="card"><div class="drop" onclick="document.getElementById('fileInput').click()">Kliknij, aby wgrać pliki<input id="fileInput" type="file" multiple hidden></div>${arr.map(x=>`<div class="item"><b>${esc(x.name)}</b><span class="tag ${visClass(x.visibility)}">${visLabel(x.visibility)}</span><button class="btn small sec" data-down="${x.id}">Pobierz</button></div>`).join('')}</div>`; }
function reports(){ const totalCost=type('finance').reduce((a,b)=>a+(+b.amount||0),0); return title('Raporty i eksport','Eksport danych marketingowych do JSON/CSV oraz szybkie podsumowania.')+`<div class="grid g4"><div class="card metric">Elementy<br><b>${S.items.length}</b></div><div class="card metric">Posty SM<br><b>${type('social').length}</b></div><div class="card metric">Wydarzenia<br><b>${type('event').length}</b></div><div class="card metric">Koszty<br><b>${totalCost} zł</b></div></div><div class="card" style="margin-top:14px"><h2>Eksport</h2><button class="btn" id="jsonExport">Eksport JSON</button> <button class="btn sec" id="csvExport">Eksport CSV</button> <button class="btn sec" onclick="print()">Drukuj / PDF</button></div>`; }
function sharing(){ const arr=type('share'); return title('Udostępnianie dla gości','Tworzenie rekordów udostępniania. Pełny publiczny dostęp wymaga Edge Function.',`<button class="btn" id="shareBtn">+ Udostępnij</button>`)+`<div class="grid g2">${arr.map(card).join('')||'<div class="card">Brak udostępnień.</div>'}</div>`; }
function integrations(){ const list=['Dropbox / pliki digital','Google Calendar','Outlook Calendar','Slack / Teams','Bitrix / CRM','Meta Ads','Google Ads','Google Sheets','Zapier / Make','SMTP / powiadomienia e-mail']; return title('Integracje','Lista systemów do podłączenia. Realne API wymaga backendu/Edge Functions.')+`<div class="grid g2">${list.map(x=>`<div class="card"><h2>${x}</h2><p class="hint">Status: do podłączenia</p></div>`).join('')}</div>`; }
function settings(){ return title('Ustawienia','Konto, hasło i konfiguracja Supabase')+`<div class="grid g2"><div class="card"><h2>Konto</h2><p>${esc(S.user.email)}</p><input class="inp" type="password" id="np1" placeholder="Nowe hasło"><br><br><input class="inp" type="password" id="np2" placeholder="Powtórz hasło"><br><br><button class="btn" id="passBtn">Zmień hasło</button></div><div class="card"><h2>Konfiguracja</h2><p class="hint">Supabase ma być ustawiony w Netlify Environment Variables. Inni użytkownicy nie muszą wpisywać URL.</p><button class="btn sec" id="clearCfg">Wyczyść lokalne nadpisanie konfiguracji</button></div></div>`; }
function visibilityPicker(v){ return `<div class="viscards"><div class="viscard ${v==='team'?'active':''}" data-vis="team"><b>👥 Zespół</b><p class="hint">Widzą wszyscy zalogowani z @${cfg.allowedDomain}</p></div><div class="viscard ${v==='private'?'active':''}" data-vis="private"><b>🔒 Prywatne</b><p class="hint">Widzę tylko ja</p></div><input type="hidden" id="f_visibility" value="${esc(v)}"></div>`; }
function formHtml(t,data={}){ const fs=fields[t]||fields.task; const currentVis=data.visibility||((t==='note')?'private':'team'); return visibilityPicker(currentVis)+`<div class="fg">${fs.map(f=>{const [k,l,tp,opt]=f, v=data[k]||''; if(tp==='select')return `<label><b>${l}</b><select class="inp" id="f_${k}">${opt.split('|').map(o=>`<option ${v==o?'selected':''}>${o}</option>`).join('')}</select></label>`; if(tp==='textarea')return `<label class="full"><b>${l}</b><textarea class="inp area" id="f_${k}" placeholder="${esc(l)}">${esc(v)}</textarea></label>`; return `<label><b>${l}</b><input class="inp" type="${tp||'text'}" id="f_${k}" value="${esc(v)}" placeholder="${esc(l)}"></label>`;}).join('')}</div>`; }
function openForm(t,id,preset={}){ const row=id?raw(id):null; t=t||row.type; const data=row?{...(row.data||{}),visibility:row.visibility}:{...preset}; modal.className='modal on'; modal.innerHTML=`<div class="box"><div class="row"><h2>${id?'Edytuj':'Dodaj'} ${t}</h2><button class="btn sec" id="closeM">✕</button></div>${formHtml(t,data)}<br><button class="btn" id="saveItem">Zapisz</button></div>`; document.getElementById('closeM').onclick=closeM; document.querySelectorAll('[data-vis]').forEach(c=>c.onclick=()=>{document.getElementById('f_visibility').value=c.dataset.vis;document.querySelectorAll('.viscard').forEach(x=>x.classList.remove('active'));c.classList.add('active');}); document.getElementById('saveItem').onclick=()=>saveItem(t,id||''); }
function closeM(){ modal.className='modal'; modal.innerHTML=''; }
async function saveItem(t,id){ const data={}, fs=fields[t]||fields.task; fs.forEach(f=>{const k=f[0], el=document.getElementById('f_'+k); data[k]=el?el.value:'';}); const visibility=document.getElementById('f_visibility')?.value||'team'; if(t==='share'&&!data.token)data.token=crypto.randomUUID?crypto.randomUUID():String(Date.now()); if(data.items)data.items=data.items.split('\n').filter(Boolean); const r=id?await sb.from('marketing_items').update({data,visibility}).eq('id',id).select():await sb.from('marketing_items').insert({type:t,data,visibility,owner_id:S.user.id}).select(); if(r.error)return toast('Błąd zapisu: '+r.error.message); closeM(); await load(); toast('Zapisano jako '+visLabel(visibility)); }
function details(id){ const r=raw(id), d=r?.data||{}; modal.className='modal on'; modal.innerHTML=`<div class="box"><div class="row"><h2>${esc(d.name||d.title||'Szczegóły')}</h2><button class="btn sec" id="closeM">✕</button></div><p><span class="tag ${visClass(r.visibility)}">${visLabel(r.visibility)}</span></p><pre style="white-space:pre-wrap;background:#f8fafc;padding:12px;border-radius:12px">${esc(JSON.stringify(d,null,2))}</pre><button class="btn" id="editD">Edytuj</button> <button class="btn danger" id="delD">Usuń</button></div>`; closeM.onclick=closeM; editD.onclick=()=>openForm(null,id); delD.onclick=()=>removeItem(id); }
async function removeItem(id){ if(!confirm('Usunąć ten element?'))return; const r=raw(id); if(r?.type==='file'&&r.data?.path)await sb.storage.from('marketing-files').remove([r.data.path]); const del=await sb.from('marketing_items').delete().eq('id',id).select(); if(del.error)return toast('Błąd usuwania: '+del.error.message); S.selected=S.selected.filter(x=>x!==id); closeM(); await load(); toast('Usunięto'); }
async function uploadFiles(e){ for(const f of e.target.files){ const path=S.user.id+'/'+Date.now()+'-'+f.name; const up=await sb.storage.from('marketing-files').upload(path,f); if(up.error){toast(up.error.message); continue;} await sb.from('marketing_items').insert({type:'file',data:{name:f.name,size:f.size,path},visibility:'team',owner_id:S.user.id}); } await load(); }
async function downloadFile(id){ const r=raw(id); const s=await sb.storage.from('marketing-files').createSignedUrl(r.data.path,60); if(s.error)return toast(s.error.message); window.open(s.data.signedUrl,'_blank'); }
function exportJSON(){downloadBlob('marketing-export.json',JSON.stringify(S.items,null,2),'application/json')} function exportCSV(){const rows=S.items.map(r=>({type:r.type,visibility:r.visibility,name:(r.data?.name||r.data?.title||''),status:(r.data?.status||''),date:(r.data?.date||r.data?.due||''),amount:(r.data?.amount||''),description:(r.data?.description||r.data?.notes||'')}));const csv=['type,visibility,name,status,date,amount,description'].concat(rows.map(r=>Object.values(r).map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','))).join('\n');downloadBlob('marketing-export.csv',csv,'text/csv')} function downloadBlob(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click()}
document.addEventListener('click',e=>{ if(e.target?.dataset?.down)downloadFile(e.target.dataset.down); if(e.target?.id==='jsonExport')exportJSON(); if(e.target?.id==='csvExport')exportCSV(); if(e.target?.id==='shareBtn')openForm('share'); if(e.target?.id==='passBtn')changePass(); if(e.target?.id==='clearCfg'){localStorage.removeItem('mh-config');location.reload();} }); async function changePass(){const a=document.getElementById('np1').value,b=document.getElementById('np2').value;if(a.length<6)return toast('Hasło min. 6 znaków');if(a!==b)return toast('Hasła nie są takie same');const r=await sb.auth.updateUser({password:a});toast(r.error?r.error.message:'Hasło zmienione')}
init();
